export type AtmosphereTokens = {
  background: string;
  paper: string;
  surface: string;
  surfaceStrong: string;
  text: string;
  muted: string;
  border: string;
  primary: string;
  primarySoft: string;
  complement: string;
  complementSoft: string;
};

export type Atmosphere = {
  id: string;
  name: string;
  emotion: string;
  primaryName: string;
  complementName: string;
  description: readonly [string, string, string];
  pigment: string;
  complementPigment: string;
  lightTokens: AtmosphereTokens;
  darkTokens: AtmosphereTokens;
};

export const atmospheres: readonly Atmosphere[] = [
  {
    id: "growth",
    name: "Growth",
    emotion: "Renewal",
    primaryName: "Sage",
    complementName: "Dusty Plum",
    description: ["Grounded.", "Growing.", "Balanced."],
    pigment: "#78947c",
    complementPigment: "#8d7187",
    lightTokens: {
      background: "#eee9df",
      paper: "#f7f2e9",
      surface: "#dce5d8",
      surfaceStrong: "#c8d8c5",
      text: "#263029",
      muted: "#677169",
      border: "#bec9ba",
      primary: "#587760",
      primarySoft: "#b9cbb8",
      complement: "#80627a",
      complementSoft: "#d8c7d4",
    },
    darkTokens: {
      background: "#17231d",
      paper: "#1d2a23",
      surface: "#293a30",
      surfaceStrong: "#34493b",
      text: "#edf1eb",
      muted: "#aab8ae",
      border: "#415548",
      primary: "#86a88d",
      primarySoft: "#3b5844",
      complement: "#c5a8c0",
      complementSoft: "#594456",
    },
  },
  {
    id: "calm",
    name: "Calm",
    emotion: "Ease",
    primaryName: "Mist Blue",
    complementName: "Soft Apricot",
    description: ["Unhurried.", "Open.", "Quiet."],
    pigment: "#86a1a7",
    complementPigment: "#c4957e",
    lightTokens: {
      background: "#ecebe5",
      paper: "#f6f4ed",
      surface: "#d9e2e1",
      surfaceStrong: "#c4d3d2",
      text: "#263033",
      muted: "#687375",
      border: "#bcc9c8",
      primary: "#617f86",
      primarySoft: "#b9cccf",
      complement: "#a67660",
      complementSoft: "#dfc9bd",
    },
    darkTokens: {
      background: "#182226",
      paper: "#202b2e",
      surface: "#2a3a3d",
      surfaceStrong: "#36494c",
      text: "#eff1ed",
      muted: "#abb7b8",
      border: "#42575a",
      primary: "#91b1b7",
      primarySoft: "#39555a",
      complement: "#d6a991",
      complementSoft: "#60483d",
    },
  },
  {
    id: "warmth",
    name: "Warmth",
    emotion: "Belonging",
    primaryName: "Warm Coral",
    complementName: "Ocean",
    description: ["Held.", "Human.", "Near."],
    pigment: "#bd806d",
    complementPigment: "#527f87",
    lightTokens: {
      background: "#f0e8df",
      paper: "#faf3e9",
      surface: "#ead7ca",
      surfaceStrong: "#dfc2b2",
      text: "#362c28",
      muted: "#776961",
      border: "#d3bfb2",
      primary: "#a86552",
      primarySoft: "#deb8a8",
      complement: "#47757d",
      complementSoft: "#b9ced0",
    },
    darkTokens: {
      background: "#281b18",
      paper: "#31231f",
      surface: "#49302a",
      surfaceStrong: "#5a3a31",
      text: "#f5ece6",
      muted: "#c5aea3",
      border: "#67463c",
      primary: "#d99680",
      primarySoft: "#694337",
      complement: "#83afb5",
      complementSoft: "#36535a",
    },
  },
  {
    id: "reflection",
    name: "Reflection",
    emotion: "Clarity",
    primaryName: "Lavender",
    complementName: "Olive",
    description: ["Soft.", "Thoughtful.", "Clear."],
    pigment: "#9a8fa8",
    complementPigment: "#7c8664",
    lightTokens: {
      background: "#eeebe9",
      paper: "#f8f4ef",
      surface: "#e2dce5",
      surfaceStrong: "#d3cad9",
      text: "#302d34",
      muted: "#716d76",
      border: "#ccc3cf",
      primary: "#776c87",
      primarySoft: "#c8bed0",
      complement: "#6f7956",
      complementSoft: "#cbd0ba",
    },
    darkTokens: {
      background: "#211e29",
      paper: "#292531",
      surface: "#393442",
      surfaceStrong: "#484054",
      text: "#f1edf2",
      muted: "#b7afbd",
      border: "#574e62",
      primary: "#b0a2c0",
      primarySoft: "#514760",
      complement: "#acb68f",
      complementSoft: "#4b513c",
    },
  },
  {
    id: "depth",
    name: "Depth",
    emotion: "Introspection",
    primaryName: "Midnight",
    complementName: "Lavender",
    description: ["Still.", "Inner.", "True."],
    pigment: "#526076",
    complementPigment: "#a394b5",
    lightTokens: {
      background: "#e9e9e7",
      paper: "#f3f2ed",
      surface: "#d6d9df",
      surfaceStrong: "#c2c8d1",
      text: "#252b35",
      muted: "#666d79",
      border: "#b9bec7",
      primary: "#48566d",
      primarySoft: "#b5bdca",
      complement: "#8d7da1",
      complementSoft: "#d3c9dc",
    },
    darkTokens: {
      background: "#111722",
      paper: "#18202d",
      surface: "#222d3d",
      surfaceStrong: "#2d3a4e",
      text: "#eef0f4",
      muted: "#a6adba",
      border: "#39485e",
      primary: "#7f91ad",
      primarySoft: "#34445b",
      complement: "#c2b2d2",
      complementSoft: "#514762",
    },
  },
  {
    id: "ocean",
    name: "Ocean",
    emotion: "Spaciousness",
    primaryName: "Ocean",
    complementName: "Warm Coral",
    description: ["Expansive.", "Steady.", "Free."],
    pigment: "#4f858b",
    complementPigment: "#bd7c68",
    lightTokens: {
      background: "#e7ece8",
      paper: "#f2f5f0",
      surface: "#cfe0dc",
      surfaceStrong: "#b7d0cd",
      text: "#223334",
      muted: "#617475",
      border: "#adc5c1",
      primary: "#3e7379",
      primarySoft: "#a8c8c7",
      complement: "#a96855",
      complementSoft: "#dfbdaf",
    },
    darkTokens: {
      background: "#102326",
      paper: "#182d30",
      surface: "#213d40",
      surfaceStrong: "#2b4c50",
      text: "#edf3f1",
      muted: "#a2b8b7",
      border: "#355a5e",
      primary: "#78aeb2",
      primarySoft: "#315b60",
      complement: "#d5947e",
      complementSoft: "#624437",
    },
  },
  {
    id: "forest",
    name: "Forest",
    emotion: "Grounding",
    primaryName: "Forest",
    complementName: "Mauve",
    description: ["Rooted.", "Sheltered.", "Alive."],
    pigment: "#55745e",
    complementPigment: "#977783",
    lightTokens: {
      background: "#e9ebe3",
      paper: "#f3f3e9",
      surface: "#d0dccb",
      surfaceStrong: "#b9ceb6",
      text: "#253029",
      muted: "#657067",
      border: "#b0c0ad",
      primary: "#476951",
      primarySoft: "#aac2aa",
      complement: "#886b77",
      complementSoft: "#d3c1c8",
    },
    darkTokens: {
      background: "#132019",
      paper: "#1a2920",
      surface: "#23372a",
      surfaceStrong: "#2d4635",
      text: "#edf1eb",
      muted: "#a5b5a9",
      border: "#38513f",
      primary: "#78a184",
      primarySoft: "#34523d",
      complement: "#c2a0ad",
      complementSoft: "#58434b",
    },
  },
  {
    id: "sand",
    name: "Sand",
    emotion: "Simplicity",
    primaryName: "Sand",
    complementName: "Slate Blue",
    description: ["Natural.", "Simple.", "Restful."],
    pigment: "#b39a78",
    complementPigment: "#64778e",
    lightTokens: {
      background: "#eee9df",
      paper: "#f8f2e7",
      surface: "#e7dcc8",
      surfaceStrong: "#d9c9ad",
      text: "#342f29",
      muted: "#776e61",
      border: "#cfc0a8",
      primary: "#967c59",
      primarySoft: "#d6c3a3",
      complement: "#5d7187",
      complementSoft: "#bec9d3",
    },
    darkTokens: {
      background: "#241f19",
      paper: "#2d2720",
      surface: "#40372b",
      surfaceStrong: "#4f4333",
      text: "#f3eee6",
      muted: "#bdb2a2",
      border: "#5d4f3d",
      primary: "#c0a47e",
      primarySoft: "#5b4b37",
      complement: "#91a5bc",
      complementSoft: "#3f4e60",
    },
  },
  {
    id: "clay",
    name: "Clay",
    emotion: "Presence",
    primaryName: "Clay",
    complementName: "Ocean Teal",
    description: ["Earthy.", "Tactile.", "Present."],
    pigment: "#a8745d",
    complementPigment: "#4e8280",
    lightTokens: {
      background: "#eee7df",
      paper: "#f8f0e7",
      surface: "#e5d4c8",
      surfaceStrong: "#d6bcae",
      text: "#372d28",
      muted: "#79685f",
      border: "#ccb7aa",
      primary: "#925f49",
      primarySoft: "#d4ad9a",
      complement: "#467976",
      complementSoft: "#b6ceca",
    },
    darkTokens: {
      background: "#261b17",
      paper: "#30231e",
      surface: "#453029",
      surfaceStrong: "#553a30",
      text: "#f4ebe6",
      muted: "#c2aaa0",
      border: "#64453a",
      primary: "#c78d72",
      primarySoft: "#654335",
      complement: "#7eaaa6",
      complementSoft: "#365654",
    },
  },
  {
    id: "lavender",
    name: "Lavender",
    emotion: "Tenderness",
    primaryName: "Lavender",
    complementName: "Midnight",
    description: ["Gentle.", "Dreaming.", "Kind."],
    pigment: "#a092af",
    complementPigment: "#525f76",
    lightTokens: {
      background: "#eeeaf0",
      paper: "#f8f4f7",
      surface: "#e3dce8",
      surfaceStrong: "#d3c8db",
      text: "#322e36",
      muted: "#736d78",
      border: "#cbc2d1",
      primary: "#81728f",
      primarySoft: "#c9bed2",
      complement: "#4f5c71",
      complementSoft: "#bdc4ce",
    },
    darkTokens: {
      background: "#201c27",
      paper: "#292330",
      surface: "#393141",
      surfaceStrong: "#483d51",
      text: "#f2edf3",
      muted: "#b9afbd",
      border: "#574a61",
      primary: "#b6a6c3",
      primarySoft: "#51455d",
      complement: "#8d9ab0",
      complementSoft: "#3d485a",
    },
  },
] as const;

