export const systemTemplates: Record<string, string[]> = {
  Health: [
    "Exercise",
    "Nutrition",
    "Sleep",
    "Recovery",
    "Preventative Care",
  ],
  Financial: [
    "Budget",
    "Income",
    "Bills",
    "Emergency Fund",
    "Savings",
    "Home Maintenance",
    "Car Maintenance",
    "Giving",
    "Investments",
  ],
  Finances: [
    "Budget",
    "Income",
    "Bills",
    "Emergency Fund",
    "Savings",
    "Home Maintenance",
    "Car Maintenance",
    "Giving",
    "Investments",
  ],
  Home: [
    "Cleaning",
    "Laundry",
    "Kitchen",
    "Yard",
    "Repairs",
    "Air Filters",
    "Organization",
  ],
  Learning: [
    "Reading",
    "Courses",
    "Practice",
    "Notes",
    "Piano or Skill Practice",
  ],
  Relationships: [
    "Family",
    "Friends",
    "Partner",
    "Communication",
    "Community",
  ],
  Energy: [
    "Morning",
    "Rest",
    "Movement",
    "Food",
    "Evening Reset",
  ],
  Work: [
    "Planning",
    "Focus",
    "Meetings",
    "Follow-up",
    "Boundaries",
  ],
  Creativity: [
    "Ideas",
    "Practice",
    "Projects",
    "Inspiration",
  ],
  Boundaries: [
    "Time",
    "Respect",
    "Space",
    "Finances",
    "Communication",
    "Digital",
  ],
  Communication: [
    "Listening",
    "Speaking",
    "Difficult Conversations",
    "Follow-up",
    "Repair",
  ],
  "Personal Growth": [
    "Mindset",
    "Confidence",
    "Reflection",
    "Purpose",
  ],
};

export function getSystemTemplates(title: string) {
  return systemTemplates[title] ?? [];
}
